 Title:  Perceptron Networks
 Aim:Implement a python program for Perceptron Networks by considering the given 
scenario. A student wants to make a decision about whether to go for a movie or not 
by looking at 3 parameters using a single neuron. The three inputs are Favorite hero, 
Exam, and Climate. Each has weights and we have a bias in the perceptron. If the 
condition is true input is 1 else input is 0, weights for Favorite hero=0.2, Exam=0.4, 
and Climate=0.2 and bias=-0.5. Output is 1. The decision is to go for a 
movie.Calculate the Accuracy 
Tools: None
 Procedure:
 1) Initialize the input vector.
 2) Train the network weights for the perceptron.
     DEEP LEARNING LABORATORY –AIL66/AD
 3) Make predictions with the perceptron.
 ● import the necessary libraries
 ●Assign the input features to x
 ● Assign the target features to y
 ● Initialize the Perceptron with the appropriate number of inputs
 ● Train the model
 ● Predict from the test dataset
 ● Find the accuracy of the model

In [8]:
import numpy as np
from sklearn.linear_model import Perceptron
from sklearn.metrics import accuracy_score

# Input: [Favorite hero, Exam, Climate]
X = np.array([
    [1, 0, 1],  # Scenario 1
    [0, 1, 1],  # Scenario 2
    [1, 1, 0],  # Scenario 3
    [0, 0, 1],  # Scenario 4
    [1, 1, 1]   # Scenario 5
])

# Expected output (1 = Go for movie, 0 = Don't go)
y = np.array([1, 1, 1, 1, 0])

# Create and configure the Perceptron model
model = Perceptron(max_iter=1000, eta0=1.0, fit_intercept=True)
model.fit(X, y)

# Predict using the same inputs
y_pred = model.predict(X)

# Print predictions
print("Predictions:", y_pred)

# Calculate accuracy
acc = accuracy_score(y, y_pred)
print("Accuracy:", acc * 100, "%")


Predictions: [1 1 1 1 1]
Accuracy: 80.0 %


In [1]:
!pip install scikit-learn 

In [4]:
import numpy as np
from sklearn.linear_model import Perceptron
from sklearn.metrics import accuracy_score

# Input: [Favorite hero, Exam, Climate]
X = np.array([
    [1, 0, 1],  # Scenario 1
    [0, 1, 1],  # Scenario 2
    [1, 1, 0],  # Scenario 3
    [0, 0, 1],  # Scenario 4
    [1, 1, 1]   # Scenario 5
])

# Expected output (1 = Go for movie, 0 = Don't go)
y = np.array([1, 1, 1, 0, 0])

# Provided weights and bias
weights = np.array([0.2, 0.4, 0.2])
bias = -0.5

# Create and configure the Perceptron model with minimum valid max_iter=1
model = Perceptron(max_iter=1, fit_intercept=True, random_state=0)
model.fit(X, y)  # Initialize model structure (minimal training)

# Manually set the weights and bias
model.coef_ = np.array([weights])  # Must be 2D array (1, n_features)
model.intercept_ = np.array([bias])  # Must be 1D array (1,)

# Predict using the same inputs
y_pred = model.predict(X)

# Print detailed results
print("Input\t\t", "Prediction\t", "Expected\t", "Result")
print("="*60)
for i in range(len(X)):
    input_str = str(X[i])
    pred = y_pred[i]
    expected = y[i]
    result = "CORRECT" if pred == expected else "WRONG"
    print(f"{input_str} \t\t{pred}\t\t {expected}\t\t {result}")

# Calculate accuracy
acc = accuracy_score(y, y_pred)
print("\nAccuracy: {:.2f}%".format(acc * 100))

Input		 Prediction	 Expected	 Result
[1 0 1] 		0		 1		 WRONG
[0 1 1] 		1		 1		 CORRECT
[1 1 0] 		1		 1		 CORRECT
[0 0 1] 		0		 0		 CORRECT
[1 1 1] 		1		 0		 WRONG

Accuracy: 60.00%


c:\Users\ASUS\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_stochastic_gradient.py:726: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  warnings.warn(
